title: CV | Jérémie Cloutier-Vilhuber
description: Jérémie's Curriculum Vitae
url: https://jeremie.cloutier-vilhuber.net
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
